gettext_0.19.%.bbappend: fix build for mingw 5.0.3
Modify CFLAGS to fix a build error caused by upgrading
mingw64 to 5.0.3: 'undefined reference to `xmlFree''

Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>